# Generated by Django 2.0.5 on 2018-05-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField()),
                ('image', models.ImageField(default=True, upload_to='media/')),
                ('body', models.TextField()),
            ],
        ),
    ]
